<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>a</string>
		<string>s</string>
		<string>asm</string>
	</array>
	<key>name</key>
	<string>CA65 Assembly</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variables</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#functions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#commands</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#labels</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#addresses</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>addresses</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?![\w_#])((\$[0-9a-fA-F]+)|(\%[01]+)|([0-9]+)|([0-9a-fA-F]h))(?![\w_#])</string>
					<key>name</key>
					<string>storage.address.ca65</string>
				</dict>
			</array>
		</dict>
		<key>commands</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\.a16|\.a8|\.align|\.assert|\.autoimport|\.bankbytes|\.bss|\.case|\.charmap|\.code|\.condes|\.constructor|\.data|\.debuginfo|\.define|\.def|\.defined|\.destructor|\.else|\.elseif|\.end|\.endenum|\.endif|\.endmac|\.endmacro|\.endproc|\.endrep|\.endrepeat|\.endscope|\.endstruct|\.enum|\.error|\.exitmac|\.exitmacro|\.export|\.exportzp|\.feature|\.fileopt|\.fopt|\.forceimport|\.global|\.globalzp|\.i16|\.i8|\.if|\.ifblank|\.ifconst|\.ifdef|\.ifnblank|\.ifndef|\.ifnref|\.ifp02|\.ifp816|\.ifpc02|\.ifpsc02|\.ifref|\.import|\.importzp|\.incbin|\.include|\.interruptor|\.linecont|\.list|\.listbytes|\.local|\.localchar|\.macpack|\.mac|\.macro|\.org|\.out|\.p02|\.p816|\.pagelen|\.pagelength|\.pc02|\.popseg|\.proc|\.psc02|\.pushseg|\.reloc|\.repeat|\.res|\.rodata|\.scope|\.segment|\.setcpu|\.smart|\.struct|\.sunplus|\.tag|\.warning|\.zeropage)\b</string>
					<key>name</key>
					<string>keyword.command.ca65</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\.addr|\.asciiz|\.byt|\.byte|\.dbyt|\.dword|\.faraddr|\.hibytes|\.lobytes|\.word)\b</string>
					<key>name</key>
					<string>keyword.definition.ca65</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>;.*$</string>
					<key>name</key>
					<string>comment.line.ca65</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\s#((\$[0-9a-fA-F]+)|(\%[01]+)|([0-9]+)|([0-9a-fA-F]h))</string>
					<key>name</key>
					<string>constant.numeric.ca65</string>
				</dict>
			</array>
		</dict>
		<key>functions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\.bankbyte|\.blank|\.concat|\.const|\.hibyte|\.hiword|\.ident|\.left|\.lobyte|\.loword|\.match|\.mid|\.ref|\.referenced|\.right|\.sizeof|\.strat|\.sprintf|\.string|\.strlen|\.tcount|\.xmatch)\b</string>
					<key>name</key>
					<string>function.language.ca65</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(adc|and|asl|bit|clc|cld|cli|clv|cmp|cpx|cpy|dec|dex|dey|eor|inc|inx|iny|lda|ldx|ldy|lsr|nop|ora|pha|php|pla|plp|rol|ror|sbc|sec|sed|sei|sta|stx|sty|tax|tay|tsx|txa|txs|tya)\b</string>
					<key>name</key>
					<string>keyword.opcode.default.ca65</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(bcc|bcs|beq|bmi|bne|bpl|brk|bvc|bvs|jmp|jsr|rti|rts)\b</string>
					<key>name</key>
					<string>keyword.opcode.control.ca65</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(jcc|jcs|jeq|jmi|jne|jpl|jvc|jvs)\b</string>
					<key>name</key>
					<string>keyword.opcode.control.longbranch.ca65</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(aac|aax|alr|anc|ane|arr|aso|asr|atx|axa|axs|dcm|dcp|dop|hlt|ins|isb|isc|jam|kil|lae|lar|las|lax|lse|lxa|oal|rla|rra|sax|sbx|skb|sha|shs|say|shx|shy|slo|skw|sre|sxa|sya|tas|top|xaa|xas)\b</string>
					<key>name</key>
					<string>invalid.deprecated.ca65</string>
				</dict>
			</array>
		</dict>
		<key>labels</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^\s*\b[\w_@]+:</string>
					<key>name</key>
					<string>entity.label.global.ca65</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s*@[\w_@]+:</string>
					<key>name</key>
					<string>entity.label.local.ca65</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.ca65</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.ca65</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.ca65</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\.</string>
							<key>name</key>
							<string>constant.character.escape.ca65</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>variables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^\s*[\w_]+\s*(?=\=)</string>
					<key>name</key>
					<string>variable.definition.ca65</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\*|\.cpu|\.paramcount|\.time|\.version)\b</string>
					<key>name</key>
					<string>variable.language.ca65</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ca65</string>
	<key>uuid</key>
	<string>eabd7ea6-d4a4-44e8-ad3c-d952e5cc95cf</string>
</dict>
</plist>
